<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AverageScore</name>
   <tag></tag>
   <elementGuidId>ac41cfec-1945-4342-963d-e9fa9a9e1060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/div[1]/div[3]/div[1]/div[2]/div[1]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;widget performance-report-padding ng-scope&quot;]/div[@class=&quot;row m0&quot;]/div[@class=&quot;col-sm-12 mt20&quot;]/div[@class=&quot;col-sm-2 pull-left&quot;]/div[@class=&quot;pull-left&quot;]/div[@class=&quot;avgScoreCircle energy-bg&quot;]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
