<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EHighestScore</name>
   <tag></tag>
   <elementGuidId>61ac035a-f421-4959-b0bf-a274cb80cb2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/div[1]/div[3]/div[1]/div[1]/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ng-binding']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/section[@class=&quot;widget performance-report-padding ng-scope&quot;]/div[@class=&quot;row m0&quot;]/div[@class=&quot;col-sm-12 mt20&quot;]/div[@class=&quot;col-sm-2 pull-left&quot;]/div[@class=&quot;pull-left&quot;]/div[@class=&quot;highestScoreCircle energy-bg&quot;]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
