<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectProjectInPortfolio</name>
   <tag></tag>
   <elementGuidId>0c810386-042f-427d-956f-e39214e3369c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@ng-show=&quot;searchingPort&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'ng-binding']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1000140374:6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths js csstransforms csstransforms3d csstransitions ng-scope&quot;]/body[@class=&quot;ng-scope nav-static chat-sidebar-container                                    modal-open              pace-done&quot;]/div[@class=&quot;modal fade ng-isolate-scope portfolio-modal portfolio-modal-wbg add-existing-project-modal in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body pl25 pb30 ng-scope&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 border-right&quot;]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/fieldset[1]/div[@class=&quot;form-group mt10&quot;]/div[@class=&quot;form-group w100p&quot;]/div[@class=&quot;input-group w100p&quot;]/div[@class=&quot;searchDropdownPort&quot;]/div[@class=&quot;projectPort_row ng-scope&quot;]/div[@class=&quot;cursor-pointer vertical_align_middle&quot;]/span[@class=&quot;ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
