<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_caret</name>
   <tag></tag>
   <elementGuidId>e892df78-97b2-49ff-a3b0-29e4dfa062a9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actions-form&quot;)/div[@class=&quot;col-md-4 ng-scope&quot;]/section[@class=&quot;widget&quot;]/div[@class=&quot;widget-body&quot;]/div[@class=&quot;mt20&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;dropdown display-inline ml10&quot;]/button[@class=&quot;btn dropdown-toggle btn-default btn-sm&quot;]/span[@class=&quot;caret&quot;]</value>
   </webElementProperties>
</WebElementEntity>
