<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select space type</name>
   <tag></tag>
   <elementGuidId>e6df50b3-6aef-44cc-a520-eca1bca448b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'space_type']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name=&quot;spaceType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>space_type</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spaceType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>formdata.spaceType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-invalid ng-invalid-required ng-animate ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add ng-pristine-remove ng-invalid-remove ng-invalid-required-remove</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-options</name>
      <type>Main</type>
      <value>item for item in spaceType</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select space typeAirport: Control TowerAirport: Distribution CenterAirport: HangarAirport: OfficeAirport: OtherAirport: Public Order/Fire/PoliceAirport: Rental Car CenterAirport: Terminal/ConcourseAirport: Vehicle Service/RepairCirculation spaceCore Learning Space: College/UniversityCore Learning Space: K-12 Elementary/Middle SchoolCore Learning Space: K-12 High SchoolCore Learning Space: Other classroom educationCore Learning Space: Preschool/DaycareData CenterHealthcare: Clinic/Other outpatientHealthcare: InpatientHealthcare: Nursing Home/Assisted LivingHealthcare: Outpatient Office (diagnostic)Industrial ManufacturingLaboratoryLodging: DormitoryLodging: Hotel/Motel/Report, Full ServiceLodging: Hotel/Motel/Resort, Limited ServiceLodging: Hotel/Motel/Resort, Select ServiceLodging: InnLodging: Other lodgingMultifamily Residential: ApartmentMultifamily Residential: CondominiumMultifamily Residential: LowriseOffice: Administrative/ProfessionalOffice: FinancialOffice: GovernmentOffice: Medical (non-diagnostic)Office: Mixed UseOffice: Other OfficePublic Assembly: Convention CenterPublic Assembly: EntertainmentPublic Assembly: Other AssemblyPublic Assembly: RecreationPublic Assembly: Social/MeetingPublic Assembly: Stadium/ArenaPublic Order and Safety: Fire/Police StationPublic Order and Safety: Other Public OrderReligious WorshipRetail: Bank BranchRetail: Convenience StoreRetail: Enclosed MallRetail: Fast FoodRetail: Grocery Store/Food MarketRetail: Open Shopping CenterRetail: Other RetailRetail: Restaurant/CafeteriaRetail: Vehicle DealershipService: Other serviceService: Post Office/Postal CenterService: Repair ShopService: Vehicle Service/RepairService: Vehicle Storage/MaintenanceSingle family home (attached)Single family home (detached)Transit: DepotTransit: LineTransit: Maintenance/StorageTransit: OfficeTransit: OtherTransit: StationTransit: Station/ElevatedTransit: Station/Open Air Ground LevelTransit: Station/UndergroundTransit: SystemWarehouse: Nonrefrigerated Distribution/ShippingWarehouse: RefrigeratedWarehouse: Self Storage UnitsWarehouse: GeneralOther</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;space_type&quot;)</value>
   </webElementProperties>
</WebElementEntity>
