<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AverageEnergyKBTU</name>
   <tag></tag>
   <elementGuidId>a55a8717-2cf5-41bc-95c8-da2819fdb61c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//th[@class='align-left'][1]/../td[1])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_lgrey fw-semi-bold ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row bg-white ng-scope&quot;]/div[@class=&quot;col-sm-12&quot;]/section[@class=&quot;widget performance_section&quot;]/div[@class=&quot;w100p&quot;]/div[@class=&quot;pull-right col-md-6&quot;]/table[@class=&quot;table analytics_table pull-right mt20&quot;]/tbody[1]/tr[@class=&quot;b_lgrey align-center&quot;]/td[@class=&quot;b_lgrey fw-semi-bold ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
