<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AvgWasteGen</name>
   <tag></tag>
   <elementGuidId>8e839a8c-4861-4514-a57a-a77f260d7af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section/div[4]/div[2]/table[1]/tbody/tr[3]/td[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
