<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CkeckBoxReview</name>
   <tag></tag>
   <elementGuidId>e5044652-9446-4bc8-9b3f-addaf4cf8f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@ng-click=&quot;updateCheckedCredits(action.CreditShortId)&quot;])[${index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@ng-click=&quot;updateCheckedCredits(action.CreditShortId)&quot;])[${index}]</value>
   </webElementProperties>
</WebElementEntity>
