<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnergyCheckBox</name>
   <tag></tag>
   <elementGuidId>e82986dc-294c-481d-b625-e1f3d3cf3d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'checkbox-PF901']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkbox-PF902</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_for_review&quot;)/section[@class=&quot;widget&quot;]/div[@class=&quot;widget-body&quot;]/div[@class=&quot;row black_color_28323a&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row pl30 pr10&quot;]/table[@class=&quot;table table-hover ml10&quot;]/tbody[1]/tr[@class=&quot;ff-ss-r ng-scope&quot;]/td[@class=&quot;vertical-align-middle text-left pl20&quot;]/div[@class=&quot;checkbox checkbox-primary&quot;]/label[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-PF902</value>
   </webElementProperties>
</WebElementEntity>
