<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParkPdfUpload</name>
   <tag></tag>
   <elementGuidId>d6cb43b9-b95c-4973-9f4b-3f2c802da5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>.//input[@onchange=&quot;angular.element(this).scope().fileNameChanged(this)&quot;] 
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
